# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 10:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='InsiderTrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('relation', models.CharField(max_length=255)),
                ('transaction_type', models.CharField(max_length=255)),
                ('owner_type', models.CharField(max_length=255)),
                ('shares_traded', models.PositiveIntegerField(null=True)),
                ('last_price', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('shares_held', models.PositiveIntegerField(null=True)),
                ('insider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='base.Insider')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('open', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('high', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('low', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('close', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('volume', models.PositiveIntegerField(null=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='base.Stock')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='insider',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Stock'),
        ),
        migrations.AlterUniqueTogether(
            name='stockprice',
            unique_together=set([('date', 'stock')]),
        ),
        migrations.AlterUniqueTogether(
            name='insidertrade',
            unique_together=set([('insider', 'date', 'transaction_type', 'shares_traded', 'last_price', 'shares_held')]),
        ),
        migrations.AlterUniqueTogether(
            name='insider',
            unique_together=set([('name', 'stock')]),
        ),
    ]
